# Generated by Django 4.2.16 on 2024-12-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('tradeid', models.IntegerField(primary_key=True, serialize=False)),
                ('notional', models.IntegerField()),
                ('counterparty', models.CharField(max_length=255)),
            ],
        ),
    ]
